export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_OK = 'GET_PRODUCTS_OK'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const GET_PRODUCTO = 'GET_PRODUCTO'
export const GET_PRODUCTO_OK = 'GET_PRODUCTO_OK'
export const GET_PRODUCTO_FAIL = 'GET_PRODUCTO_FAIL'